feat: added film recommendations to users controller and tests for th…
vvbakhanovich/java-filmorate pull request #12
Opened 2024-01-31 05:49 UTC by elenabokhan13

Сделала метод для рекомендаций фильмов и написала тест для его проверки.

2024-01-31 06:48 UTC, vvbakhanovich requested changes

2024-01-31 06:48 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                (rs, rowNum) -> Long.valueOf(rs.getInt("film_id"))));
Так как ты обращаешься к таблице film_like, то лучше создать метод по получению айдишников лайкнутых пользователем фильмов в FilmLikeDbStorage.

2024-01-31 06:48 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        Collection<User> allUsers = findAll();
Лучше перенести логику предоставления рекомандаций в сервис и оттуда вызвать подобные методы)

2024-01-31 06:48 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                        (rs, rowNum) -> Long.valueOf(rs.getInt("film_id")))));
Тут как раз возникает проблема n+1 запроса, так как для каждого пользователя из БД мы каждый раз ищем его лайкнутые фильмы. Можно в FilmLikeDbStorage создать метод, который, например, мапу где ключ - айди пользователя, а значение лист или сет айдишников лайкнутых фильмов)

2024-01-31 06:48 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                    if (currentUserLikedFilms.size() < likedFilms.size()) {
Можно ли здесь объединить в один if через &&?

2024-01-31 06:48 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                } else if (currentUserLikedFilms.size() == maxLikes) {
Может здесь тоже можно запихнуть в предыдущий if через >=?

2024-01-31 06:48 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +            filmsRecommendation.add(filmDbStorage.findById(filmId));
Тут тоже появилась проблема n+1 запроса. Попробуй сделать в FilmDbStorage метод, который будет одним запросом получать список фильмов по вхождению айдишников. 
https://www.baeldung.com/spring-jdbctemplate-in-list

2024-01-31 06:48 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +    }
Добавь пожалуйста javaDoc (краткое описание что твой метод делает, принимает и возвращает). Для этого начни печатать /** и нажми энтер)

2024-01-31 06:48 UTC, vvbakhanovich commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +    void testGetRecommendationsList() {
Может стоит добавить еще тесты? Когда нету пересечний по лайкам или когда лайки равны?

2024-01-31 06:49 UTC, vvbakhanovich approved these changes

2024-01-31 12:00 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                (rs, rowNum) -> Long.valueOf(rs.getInt("film_id"))));
я в общем совсем все переиграла. я согласна, что у меня все бизнес логика ушла в сторидж, а она должна быть в сервисе и работать с любыми сториджами. теперь я выгружаю все данные из таблицы (и юзеров , и фильмы), поэтому метод может быть в любом месте, логичнее его оставить в юзер сторидже, т.к. метод из юзер контролера

2024-01-31 12:00 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        Collection<User> allUsers = findAll();
это готово

2024-01-31 12:01 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                        (rs, rowNum) -> Long.valueOf(rs.getInt("film_id")))));
это тоже теперь по другому, выгружаю все данные одним запросом и их матчу в мапу

2024-01-31 12:01 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                    if (currentUserLikedFilms.size() < likedFilms.size()) {
здесь можно )))) сначала была просто другая логика, ее часть ушла, а эта часть осталась так :D

2024-01-31 12:02 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                } else if (currentUserLikedFilms.size() == maxLikes) {
вот здесь нельзя, а потому что у этих двух условий разная логика. если их объединить, то потом все равно нужно проверять на равенство. от этой проверки не уйти, а так она выглядит прозрачнее

2024-01-31 12:02 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +            filmsRecommendation.add(filmDbStorage.findById(filmId));
это поправила

2024-01-31 12:05 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +    }
это тоже добавила

2024-01-31 12:05 UTC, elenabokhan13 commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +    void testGetRecommendationsList() {
тесты добавила

2024-01-31 12:39 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        List<List<Long>> userLikedFilms = jdbcTemplate.query(filmsIdsSql, (resultSet, rowNum) -> {
Может лучше заменить List<List<Long>> на мапу Map<Long, Set<Long>>, где ключ userId, а в качестве значений список filmId. Можно написать экстарктор по аналогии с тем, что в классе User (метод extractToUserList). Только я бы все это переместил в filmLikeDbStorage, потому что к таблице с юзерами это не имеет отношения)

2024-01-31 12:39 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        for (List userLikes : userLikedFilms) {
Потерялся дженерик у List)

2024-01-31 12:39 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                result.put((Long) userLikes.get(0), films);
При использовании дженерика не нужен будет каст

2024-01-31 12:39 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +            if (result.get(userLikes.get(0)) == null) {
Если использовать мапу из коммента выше, то получится чуть более лаконично)

2024-01-31 12:39 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                result.put((Long) userLikes.get(0), films);
Аналогичные комментарии)

2024-01-31 12:39 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        }
Снова пресловутая проблема n+1) Лучше передать в метод сет айдишников и он вернет уже список фильмов. В SQL запрос будет выглядеть примерно так: SELECT * FROM film WHERE id IN (1, 2, 3) и т.д. Ссылку вроде скидывал как это можно в jdbcTemplate реализовать)

2024-01-31 12:39 UTC, vvbakhanovich commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +        userService = new UserServiceImpl(userStorage, filmDbStorage, friendshipStorage);
Насколько я понял нам методы сервиса тестировать не надо, поэтому и этой сущности быть не должно

2024-01-31 12:39 UTC, vvbakhanovich commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +                .map(FilmMapper::toModel).collect(Collectors.toList());
Лучше тестировать методы UserDbStorage, то есть то, что должно из БД вытаскиваться

2024-01-31 12:39 UTC, vvbakhanovich commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +                .map(FilmMapper::toModel).collect(Collectors.toList());
Здесь также, лучше тестировать методы UserDbStorage, то есть то, что должно из БД вытаскиваться

2024-01-31 12:39 UTC, vvbakhanovich commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +                .map(FilmMapper::toModel).collect(Collectors.toList());
И здесь)

2024-02-01 04:28 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        for (List userLikes : userLikedFilms) {
аааа так вот почему он ругаться начал ))

2024-02-01 04:28 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                result.put((Long) userLikes.get(0), films);
+

2024-02-01 04:31 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        List<List<Long>> userLikedFilms = jdbcTemplate.query(filmsIdsSql, (resultSet, rowNum) -> {
аааа я забываю, что у тебя есть отдельный сторидж под лайки. так-то мне кажется, можно и здесь оставить, т.к. я делаю мапу про юзеров. могу и перенести, если для тебя это прям принципиально :) 

но вот я что-то не могу никак понять, как сразу из таблицы выгрузить такую мапу. у нас ведь у одного пользователя может быть несколько строк с фильмами, которые он залайкал. все равно нужно потом по ним всем проходится и дубляжи собирать. а если делать группировку, то у меня выгружаются данные по количеству лайков у юзера без айдишников фильмов. в общем, хэлп!

2024-02-01 04:33 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +            if (result.get(userLikes.get(0)) == null) {
+

2024-02-01 04:33 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                result.put((Long) userLikes.get(0), films);
++

2024-02-01 04:37 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        }
я здесь так оставила, потому что мне все-таки кажется логичнее эту часть логики оставить именно в сервисе. т.к. сервис должен быть универсальным и работать с любой базой, как бы не хранились данные. если логику по рекомендации убрать в сторидж, то это значит, что эту же логику нужно будет заново реализовывать в каждом сторидже, который мы будем подключать. до этого у нас все методы были простые, поэтому сервис такой пустой. но по сути, в нем обычно больше кода, т.к. мы не просто выгружаем данные, но еще и обрабатываем их

2024-02-01 04:37 UTC, elenabokhan13 commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +        userService = new UserServiceImpl(userStorage, filmDbStorage, friendshipStorage);
я отталкивалась от того, что нам нужно протестировать именно функциональность, а т.к. сама логика в сервисе, то его и нужно тетсировать в данном случае. сторидж здесь просто выгружает данные

2024-02-01 04:38 UTC, elenabokhan13 commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +                .map(FilmMapper::toModel).collect(Collectors.toList());
но тогда мы не протестрируем саму логику. в постман тестах, например, именно логика прослеживается, например, когда лайки одинаковые

2024-02-01 04:38 UTC, elenabokhan13 commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +                .map(FilmMapper::toModel).collect(Collectors.toList());
аналогично комментарию выше

2024-02-01 04:39 UTC, elenabokhan13 commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +                .map(FilmMapper::toModel).collect(Collectors.toList());
аналогично комментарию выше выше )))

2024-02-01 11:58 UTC, vvbakhanovich reviewed
Отличная работа, осталось чуть чуть стиль поправить)

2024-02-01 11:58 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmLikeStorage.java
> +    Map<Long, Set<Long>> usersAndFilmLikes();
Добавь глагол в начале, чтобы было понятнее то, что метод делает) Например getAllUsersAndFilmLikes

2024-02-01 11:58 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmLikeDbStorage.java
> +    public Map<Long, Set<Long>> usersAndFilmLikes() {
Чисто ради лаконичности, публичные методы лучше размещать до приватных)

2024-02-01 11:58 UTC, vvbakhanovich commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +        assertThat(filmRecommendations.get(new Long(1)))
Может new Long(1) заменить просто на 1L ?)

2024-02-01 11:58 UTC, vvbakhanovich commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +        assertThat(filmRecommendations.get(new Long(2)))
Тут тоже я бы заменил на 2L )

2024-02-01 12:06 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmLikeStorage.java
> +    Map<Long, Set<Long>> usersAndFilmLikes();
готово

2024-02-01 12:07 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmLikeDbStorage.java
> +    public Map<Long, Set<Long>> usersAndFilmLikes() {
готово

2024-02-01 12:07 UTC, elenabokhan13 commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +        assertThat(filmRecommendations.get(new Long(1)))
готово

2024-02-01 12:07 UTC, elenabokhan13 commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +        assertThat(filmRecommendations.get(new Long(2)))
готово

2024-02-01 12:38 UTC, merged