Рефакторинг: лайки → оценки
vvbakhanovich/java-filmorate pull request #31
Opened 2024-02-11 10:54 UTC by vvbakhanovich

В таблице film_like было добавлено целочисленное поле rating. При лайке фильма пользователь может поставить оценку от 0 до 10 (0 - пользователь решил не ставить оценку).
Были изменено поле long likes на double rating в Film и FilmDto. Рейтинг фильма рассчитывается как среднее арифметическое (сумма рейтингов / количество пользователей, оценивших фильм). 
В предыдущей версии пользователь мог ставить несколько оценок одному и тому же фильму. Теперь при повторном лайке обновляется оценка, которую поставил пользователь. Написаны тесты.
Обновлен алгоритм получения рекомендаций. Для рекомендаций выбирается пользователь с наилучшим совпадениям по оценкам одних и тех же фильмов. Написаны тесты.

2024-02-12 06:34 UTC, ayzatmr approved these changes

2024-02-13 23:50 UTC, mysosnovskaya requested changes
Сделала ревью. Основные замечания, конечно, по алгоритму. В целом он понятен, при желании можно с ним разобраться, но я всё равно рекомендую ещё поработать над кодом. Для будущего точно будет полезно) Обязательно разбить на методы (если возникнут трудности, то можно прийти ко мне в личку, вместе подумаем), изменить названия некоторых переменных, изменить подход к комментированию. 

В остальном коде никаких критичных замечаний нет, однако я всё же рекомендую внести предложенные изменения, т.к. они приближают код к коду реального проекта. Если есть вопросы/аргументы/ответы, то их лучше написать в ответ на мой комментарий в ПРе. 

После завершения работы над ПРом, нужно сообщить мне об этом в личку) Приду и посмотрю ещё раз :)

2024-02-13 23:50 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/dto/FilmDto.java
> +import javax.validation.constraints.*;
Импорты лучше всегда оставлять полными и избегать замены звездочками. Это в IDEA настраивается (settings -> editor -> code style -> java -> imports)

2024-02-13 23:50 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private double rating; //количество лайков от пользователей
Комментарий уже не подходит. Я бы вообще комментарий не писала, вроде и без него понятно, что это за поле.

2024-02-13 23:50 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    FilmDto likeFilm(long filmId, long userId, int rating);
Сомневаюсь, что имя rating подходящее. Может быть  mark?

2024-02-13 23:50 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +    @Transactional
Почему раньше было без этой аннотации, а сейчас она добавилась? Изменений в методе нет

2024-02-13 23:50 UTC, mysosnovskaya commented on src/main/resources/schema.sql
>  CREATE TABLE IF NOT EXISTS FILM_LIKE(
Мне кажется, like уже везде в коде нужно убирать, он имеет другой смысл (бинарный: нравится или нет). Таблицу можно назвать film_marks, а колонку - mark (оценка).

2024-02-13 23:50 UTC, mysosnovskaya commented on src/test/java/ru/yandex/practicum/filmorate/storage/FilmDbStorageTest.java
> +    void testAddTwoLikesFromOneUser() {
Можно ещё добавить тест, что если у фильма нет оценок, то рейтинг должен быть... Каким? Наверное, null. Но точно не должно быть никаких ошибок.

2024-02-13 23:50 UTC, mysosnovskaya commented on src/test/java/ru/yandex/practicum/filmorate/storage/FilmDbStorageTest.java
> +        filmDbStorage.addLikeToFilm(film.getId(), user.getId(), 10);
Можно разные оценки добавлять, чтобы интереснее было :)

2024-02-13 23:50 UTC, mysosnovskaya commented on src/test/java/ru/yandex/practicum/filmorate/integration/UserServiceTest.java
> +public class UserServiceTest {
На будущее: скоро (в 15 спринте) изучим mock (моки), они бы здесь очень пригодились для тестирования. Сейчас ничего переделывать не нужно, просто комментарий о том, что метод рекомендаций лучше тестировать другим способом. Текущий очень громоздкий.

2024-02-13 23:50 UTC, mysosnovskaya commented on src/test/java/ru/yandex/practicum/filmorate/integration/UserServiceTest.java
> +        user3 = User.builder()
Чтобы избавиться от дублирования кода, можно добавить метод 
private User createTestUser(int id);
который будет создавать нового пользователя с помощью билдера, проставляя ему нужные значения полей (конкатенация с переданным id). С фильмами аналогично.

2024-02-13 23:50 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        int positiveRating = 6;
Это должно быть константой (поле класса private static final...)

2024-02-13 23:50 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +            Map<Long, Integer> currentUserFilmRating = usersLikes.get(userId); // фильмы и их оценки от текущего пользователся
Эта мапа уже есть в строке 185, разве нет?

2024-02-13 23:50 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        long bestUserId = 0; // начальное значение id пользователя с наибольшим количеством совпадений по оценкам
Лучше Long и null использовать, т.к. 0 - это вполне конкретное значение id. Ну или на крайний случай -1 можно, но я всё-таки за null.

2024-02-13 23:50 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        int numberOfLikedFilms = 0; // начальное значение для количества фильмов, которым пользователь поставил оценки
Не вижу, где это значение обновляется?

2024-02-13 23:50 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
>      public Collection<FilmDto> showRecommendations(long id) {
Этот метод нужно разбить на несколько. Например, код из первого цикла for можно вынести в отдельный метод (нужно придумать ему хорошее понятное название). Код из второго цикла for также можно попробовать вынести. Если вдруг у метода будет много параметров, то в таком случае создается специальный класс - ShowRecommendationsParams (или можно к названию алгоритма как-то привязать, главное - в конце названия добавить Params). Это такой dto класс для передачи большого количества данных между методами. Например, там могут быть поля currentNumberOfLikedFilms, currentDiff, currentNumberOfMatches. Название класса может быть содержать Current (надо ещё подумать, как лучше назвать). Частая практика для подобных ситуаций)

2024-02-13 23:50 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +            if (userId == id) { // искомого пользователя пропускаем
Нужно ещё поработать с комментариями к коду. Например, этот можно удалить, т.к. в целом данная строка кода вопросов не вызывает. Общее описание алгоритма можно написать в javadoc перед методом. Только единичные строки могут быть прокомментированы. Лучше передавать смысл кода через понятные названия переменных и вынос кода в отдельные понятно названные методы.

2024-02-13 23:50 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        double bestMatch = Double.MAX_VALUE; // начальное значение для лучшего соотношения совпавших оценок
Как будто бы названию этой переменной что-то не хватает. Может быть bestMatchValue (значение наилучшего совпадения)? Может быть можно как-то ещё назвать, чтобы было понятно, что чем оно меньше, тем лучше.

2024-02-14 14:13 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/dto/FilmDto.java
> +import javax.validation.constraints.*;
Спасибо за рекомендацию)

2024-02-14 14:14 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private double rating; //количество лайков от пользователей
Комментарии убрали

2024-02-14 14:14 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    FilmDto likeFilm(long filmId, long userId, int rating);
Заменили на mark

2024-02-14 14:16 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +    @Transactional
Решили добавить, поскольку в методе изменяется содержимое БД и потом идет запрос на получение элемента.

2024-02-14 14:17 UTC, vvbakhanovich commented on src/test/java/ru/yandex/practicum/filmorate/storage/FilmDbStorageTest.java
> +    void testAddTwoLikesFromOneUser() {
Добавили, БД возвращает 0.0, если у фильмов нет оценок)

2024-02-14 14:17 UTC, vvbakhanovich commented on src/test/java/ru/yandex/practicum/filmorate/storage/FilmDbStorageTest.java
> +        filmDbStorage.addLikeToFilm(film.getId(), user.getId(), 10);
Сделали интереснее))

2024-02-14 14:18 UTC, vvbakhanovich commented on src/test/java/ru/yandex/practicum/filmorate/integration/UserServiceTest.java
> +        user3 = User.builder()
Спасибо за совет, так намного лучше)

2024-02-14 14:19 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        int positiveRating = 6;
Сделали

2024-02-14 14:20 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +            Map<Long, Integer> currentUserFilmRating = usersLikes.get(userId); // фильмы и их оценки от текущего пользователся
На 185 строке мапа принадлежит пользователю, которому нужны рекомендации, а здесь по очереди получаем мапы с оцененными фильмами остальных пользователей) Заменили на Set<FilmMark>

2024-02-14 14:22 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        int numberOfLikedFilms = 0; // начальное значение для количества фильмов, которым пользователь поставил оценки
Не обновлялось, теперь обновляется)

2024-02-14 14:23 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
>      public Collection<FilmDto> showRecommendations(long id) {
Разделили на два метода и также добавили класс RecommendationsCurrentParams

2024-02-14 14:23 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +            if (userId == id) { // искомого пользователя пропускаем
Комментарии убрали

2024-02-14 14:23 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        double bestMatch = Double.MAX_VALUE; // начальное значение для лучшего соотношения совпавших оценок
Названия переменных поправили

2024-02-14 15:32 UTC, mysosnovskaya requested changes
На мой взгляд, уже стало сильно лучше =) Написала ещё некоторые предложения по улучшению. Думаю, после них уже будет финальное ревью.

2024-02-14 15:32 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmStorage.java
> +    void addMarkToFilm(long filmId, long userId, Integer rating);
Всё-таки не rating, а mark

2024-02-14 15:32 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmMark.java
> +    private long filmId;
Сюда как будто бы ещё userId просится. Чисто по логике)

2024-02-14 15:32 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +    private static final int POSITIVE_RATING = 6;
Может быть лучше POSITIVE_RATING_STARTS_FROM? Или MIN_POSITIVE_RATING_VALUE? Какое-то обозначение того, что это минимальное/начальное значение положительного рейтинга

2024-02-14 15:32 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        Set<FilmMark> searchedUserFilmMarks = usersFilmMarks.get(id);
Можно назвать requesterFilmMarks. Requester - "запрашиватель", тот, кто запрашивает для себя рекомендации)

2024-02-14 15:32 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        Set<FilmMark> searchedUserFilmMarks = usersFilmMarks.get(id);
Кстати, и id можно переименовать в requesterId

2024-02-14 15:32 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        Set<Long> matchedUserMarkedFilmIds = usersFilmMarks.get(userIdWithClosestMarks).stream()
Можно чуть проще. Во-первых, вместо Set<FilmMark> searchedUserFilmMarks можно сразу хранить Set<Integer> markedFilmIdsOfRequester. А во-вторых, операцию removeAll можно заменить на filter при формировании matchedUserMarkedFilmIds (после .map(...) сделать .filter(...) и только потом собирать всё это в Set)

2024-02-14 15:32 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +    private Long findUserIdWithClosestMarks(Map<Long, Set<FilmMark>> usersFilmMarks, long searchedUserId) {
Эти два приватных метода лучше поменять местами, чтобы было "по ходу чтения". Ну это так, мелочь, но ещё немного код приятнее становится)

2024-02-14 15:32 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/dto/RecommendationsCurrentParams.java
> +    private int currentDiff;
В названиях полей уже можно не использовать current, т.к. уже из названия класса это понятно)

2024-02-14 15:32 UTC, mysosnovskaya commented on src/test/java/ru/yandex/practicum/filmorate/integration/UserServiceTest.java
> +public class UserServiceTest {
Мне кажется, ещё не хватает теста, когда у всех других пользователей отрицательные оценки) А вообще сейчас тесты очень хорошо выглядят. И по коду, и по сценариям. Отличная работа)

2024-02-14 15:32 UTC, mysosnovskaya commented on src/test/java/ru/yandex/practicum/filmorate/storage/FilmDbStorageTest.java
> +    void testAddTwoLikesFromOneUser() {
Интересно, насколько это с точки зрения бизнес-логики верно. По идее в таком случае на фронт нужно вернуть null, чтобы он написал "рейтинг не определен". Ну ладно, давай пока 0 оставим)

2024-02-15 06:35 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmStorage.java
> +    void addMarkToFilm(long filmId, long userId, Integer rating);
Еще в контроллере остался rating, теперь все mark)

2024-02-15 06:35 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmMark.java
> +    private long filmId;
Добавили

2024-02-15 06:36 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +    private static final int POSITIVE_RATING = 6;
Да, MIN_POSITIVE_RATING_VALUE гораздо лучше, спасибо)

2024-02-15 06:36 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        Set<FilmMark> searchedUserFilmMarks = usersFilmMarks.get(id);
Стало читабельнее)

2024-02-15 06:36 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +    private Long findUserIdWithClosestMarks(Map<Long, Set<FilmMark>> usersFilmMarks, long searchedUserId) {
Поменяли

2024-02-15 07:02 UTC, vvbakhanovich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        Set<Long> matchedUserMarkedFilmIds = usersFilmMarks.get(userIdWithClosestMarks).stream()
Set markedFilmIdsOfRequester сразу хранить не получится, нам нужны именно FilmMark для поиска рекомендаций. А removeAll заменили на filter)

2024-02-15 07:02 UTC, vvbakhanovich commented on src/test/java/ru/yandex/practicum/filmorate/integration/UserServiceTest.java
> +public class UserServiceTest {
Спасибо) Еще пару тестов добавили

2024-02-15 14:33 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        Set<Long> matchedUserMarkedFilmIds = usersFilmMarks.get(userIdWithClosestMarks).stream()
Не поняла. Отписала в личку.

2024-02-15 22:17 UTC, mysosnovskaya approved these changes
На мой взгляд, код стал значительно понятнее) Хорошая работа!

2024-02-16 05:47 UTC, merged